return {
  "catppuccin",
  optional = true,
  opts = {
    flavour = "mocha",
    background = { light = "latte", dark = "mocha" },
    integrations = {
      blink_cmp = true,
      dap = {
        enabled = true,
        enable_ui = true,
      },
      gitsigns = true,
      lsp_trouble = true,
      mason = true,
      neotest = true,
      native_lsp = {
        enabled = true,
        virtual_text = {
          errors = { "italic" },
          hints = {},
          warnings = { "italic" },
          information = {},
        },
        underlines = {
          errors = { "undercurl" },
          hints = {},
          warnings = { "undercurl" },
          information = {},
        },
      },
      overseer = true,
      telescope = true,
      treesitter = true,
    },
    term_colors = false,
    styles = {
      comments = {},
      keywords = { "italic" },
    },
    compile = {
      enabled = true,
      path = vim.fn.stdpath("cache") .. "/catppuccin",
    },
    dim_inactive = {
      enabled = true,
      shade = "dark",
      percentage = 0.15,
    },
    custom_highlights = function(c)
      return {
        BlinkCmpDocBorder = { fg = c.blue },
        BlinkCmpKind = { fg = c.blue },
        BlinkCmpMenu = { fg = c.text },
        BlinkCmpMenuBorder = { fg = c.blue },
        BlinkCmpSignatureHelpActiveParameter = { fg = c.mauve },
        BlinkCmpSignatureHelpBorder = { fg = c.blue },
        ColorColumn = { bg = c.mantle },
        Cursor = { fg = c.base, bg = "#d9e0ee" },
        MarkviewPalette1Fg = { fg = "#d9e0ee" },
        TSConstBuiltin = { fg = c.maroon },
        TermCursor = { fg = "#000000", bg = "#B7BDF8" },
        TreesitterContextLineNumber = { fg = "#494D64", bg = "#1e2030" },
        Unvisited = { bg = "#34344F" },
        ["@constant.builtin"] = { fg = c.maroon },
        rainbow1 = { fg = c.red, bg = "#302D41" },
        rainbow2 = { fg = c.peach, bg = "#302D41" },
        rainbow3 = { fg = c.yellow, bg = "#302D41" },
        rainbow4 = { fg = c.green, bg = "#302D41" },
        rainbow5 = { fg = c.sapphire, bg = "#302D41" },
        rainbow6 = { fg = c.lavender, bg = "#302D41" },
      }
    end,
  },
}
